import type { BrokerOrchestrationResponse } from "@/types/broker";
import type { ComparableItem, RentFairPriceData, RentFairPriceRequest } from "@/types/valuation";

export const sampleRequest: RentFairPriceRequest = {
  lat: 30.0444,
  lng: 31.2357,
  property_type: "Apartment",
  property_category: "residential_rent",
  bedrooms: 3,
  bathrooms: 2,
  size_sqm: 150,
  target_price_egp: 95000,
  amenities: ["BA", "SE"],
  furnishing_status: "furnished",
  floor_number: 8,
  compound_name: "Nile Quarter",
  view_type: "river",
  building_quality: "premium",
};

export const sampleComparable: ComparableItem = {
  listing_id: "comp-001",
  price_egp: 90000,
  size_sqm: 150,
  price_per_sqm: 600,
  property_type: "Apartment",
  bedrooms: 3,
  bathrooms: 2,
  area_id: 10,
  area_name: "Central Cairo",
  lat: 30.047,
  lng: 31.238,
  location_text: "Central Cairo",
  images_count: 8,
  retrieval_tier: 1,
  tier_label: "same compound/neighborhood",
  reason_code: "SAME_AREA_MATCH",
  radius_m: 500,
  dist_m: 420,
  age_days: 12,
  weight: 0.82,
  weight_components: {
    distance: 0.72,
    size_similarity: 1,
    recency: 0.84,
    feature_similarity: 1,
  },
  weighted_contribution: 0.62,
  confidence_contribution: 0.54,
  similarity_score: 1,
  geographic_similarity: 0.72,
  distance_weight: 0.72,
  recency_weight: 0.84,
  evidence_rank: 1,
  property_category: "residential_rent",
  amenities: [],
  normalized_amenities: ["balcony", "security"],
  canonical_amenity_symbols: ["BA", "SE"],
  unknown_amenity_codes: [],
  furnishing_status: "furnished",
  floor_number: 8,
  compound_name: "Nile Quarter",
  view_type: "river",
  building_quality: "premium",
  feature_similarity: 1,
  feature_similarity_components: {
    amenities: 1,
  },
  feature_explanation: {
    matched_amenities: ["balcony", "security"],
    missing_amenities: [],
  },
  feature_overlap: {
    matched_amenities: ["balcony", "security"],
    missing_amenities: [],
    extra_amenities: [],
  },
  amenity_similarity: 1,
  amenity_explanation: {
    matched_amenities: ["balcony", "security"],
    missing_amenities: [],
    extra_amenities: [],
  },
  amenity_metadata: [
    {
      symbol: "BA",
      name: "Balcony",
      normalized: "balcony",
      valuation_weight: 0.04,
    },
  ],
  filter_status: {
    hard_guardrails: "kept",
    mad_outlier: "kept",
  },
};

export const secondaryComparable: ComparableItem = {
  ...sampleComparable,
  listing_id: "comp-002",
  price_egp: 85000,
  dist_m: 900,
  age_days: 140,
  weight: 0.4,
  weighted_contribution: 0.3,
  confidence_contribution: 0.18,
  similarity_score: 0.55,
  feature_similarity: 0.5,
  evidence_rank: 2,
  building_quality: "standard",
  lat: 30.051,
  lng: 31.242,
};

export const sampleValuation: RentFairPriceData = {
  fair_price_egp: 90000,
  range_low_egp: 82000,
  range_high_egp: 105000,
  flag: "OK",
  tier_used: 1,
  comps_count: 12,
  confidence: {
    score: 0.82,
    label: "High",
    factors: {
      count: 1,
      tier: 1,
      kept_ratio: 1,
      dispersion: 0.9,
      distance: 0.97,
      recency: 0.8,
      similarity: 1,
      amenity_similarity: 1,
      valuation_evidence: 0.84,
      location_resolution: 0.82,
    },
    dimensions: {
      valuation_evidence: {
        score: 0.84,
        label: "High",
        factors: {
          count: 1,
        },
      },
      location_resolution: {
        score: 0.82,
        source: "MANUAL_COORDINATES",
        precision_level: "ROOFTOP",
      },
    },
  },
  explanation: [
    "12 similar listings found using same compound/neighborhood around Central Cairo.",
    "Fair price computed using weighted median.",
  ],
  explanation_trace: [
    {
      reason_code: "SAME_AREA_MATCH",
      details: {
        radius_m: 500,
        comps_found: 12,
      },
    },
    {
      reason_code: "CONFIDENCE_FACTORS",
      weight: 0.82,
      details: {
        confidence_score: 0.82,
        tier: 1,
      },
    },
    {
      reason_code: "FEATURE_SIMILARITY_APPLIED",
      weight: 1,
      details: {
        matched_amenities: ["balcony", "security"],
        missing_amenities: [],
      },
    },
  ],
  retrieval_trace: [
    {
      tier: 1,
      tier_label: "same compound/neighborhood",
      reason_code: "SAME_AREA_MATCH",
      scope: "same_area",
      radius_m: 500,
      comps_found: 12,
      threshold: 10,
      shortfall: 0,
      attempt_index: 1,
      status: "selected",
      selected: true,
      radius_expansion_m: null,
    },
  ],
  spatial_diagnostics: {
    subject: {
      lat: 30.0444,
      lng: 31.2357,
      area_id: 10,
      area_name: "Central Cairo",
    },
    retrieval_radius_m: 500,
    distance_band_counts: {
      "0_500m": 1,
      "500_1000m": 0,
    },
    cluster_quality: "high_quality_cluster",
  },
  evidence_summary: {
    authoritative_valuation_frozen: true,
    valuation_mutation_allowed: false,
    property_category: "residential_rent",
    valuation_contract: {
      category: "residential_rent",
      label: "Residential rent",
      value_basis: "monthly_rent",
    },
    amenity_intelligence: {
      average_amenity_similarity: 1,
      comps_scored: 1,
      matched_amenities_observed: ["balcony", "security"],
      missing_amenities_observed: [],
    },
    guardrails: {
      kept: 12,
      removed: 0,
    },
    mad: {
      kept: 12,
      removed: 0,
      metric: "price_per_sqm",
    },
  },
  area: {
    name: "Central Cairo",
    area_id: 10,
  },
  resolved_location: {
    lat: 30.0444,
    lng: 31.2357,
    precision_level: "ROOFTOP",
  },
  property_category: "residential_rent",
  valuation_contract: {
    category: "residential_rent",
    label: "Residential rent",
    value_basis: "monthly_rent",
    governance: {
      amenities_override_pricing: false,
    },
  },
  amenity_intelligence: {
    property_category: "residential_rent",
    contract_label: "Residential rent",
    average_amenity_similarity: 1,
    comps_scored: 1,
    matched_amenities_observed: ["balcony", "security"],
    missing_amenities_observed: [],
  },
  debug: {},
  top_comps: [sampleComparable],
};

export const sampleBrokerResponse: BrokerOrchestrationResponse = {
  session_id: "broker-session-1",
  intent: "valuation_explanation",
  response: {
    executive_summary: "The valuation is supported by a high-confidence comparable cluster.",
    valuation_interpretation: "The fair rent sits inside the returned deterministic range.",
    comparable_reasoning: "Comparable evidence is anchored by nearby listings with strong feature similarity.",
    district_insights: "District context is limited to the resolved valuation area and returned evidence.",
    confidence_explanation: "Confidence is high because comparable depth and similarity are strong.",
    opportunity_risk_notes: ["Monitor spread widening before repricing.", "Do not infer external demand signals."],
    analytical_conclusion: "The target remains aligned with the deterministic valuation evidence.",
    authoritative_values: {
      fair_price_egp: sampleValuation.fair_price_egp,
      range_low_egp: sampleValuation.range_low_egp,
      range_high_egp: sampleValuation.range_high_egp,
      flag: sampleValuation.flag,
      tier_used: sampleValuation.tier_used,
      comps_count: sampleValuation.comps_count,
      confidence_score: sampleValuation.confidence.score,
      confidence_label: sampleValuation.confidence.label,
    },
    evidence_ids: ["valuation_summary", "comp-001"],
    referenced_comp_listing_ids: ["comp-001"],
  },
  grounding: {
    status: "passed",
    violations: [],
    checked_values: {},
  },
  context: {
    intent: "valuation_explanation",
    session_id: "broker-session-1",
    user_message: "Explain the valuation",
    valuation_summary: {
      fair_price_egp: sampleValuation.fair_price_egp,
      range_low_egp: sampleValuation.range_low_egp,
      range_high_egp: sampleValuation.range_high_egp,
      flag: sampleValuation.flag,
      tier_used: sampleValuation.tier_used,
      comps_count: sampleValuation.comps_count,
      confidence_score: sampleValuation.confidence.score,
      confidence_label: sampleValuation.confidence.label,
      area: sampleValuation.area,
      property_category: sampleValuation.property_category,
      valuation_contract: sampleValuation.valuation_contract,
      amenity_intelligence: sampleValuation.amenity_intelligence,
    },
    comparable_evidence: [
      {
        evidence_id: "comp-001",
        listing_id: sampleComparable.listing_id,
        price_egp: sampleComparable.price_egp,
        size_sqm: sampleComparable.size_sqm,
        bedrooms: sampleComparable.bedrooms,
        bathrooms: sampleComparable.bathrooms,
        area_name: sampleComparable.area_name,
        distance_m: sampleComparable.dist_m,
        age_days: sampleComparable.age_days,
        weight: sampleComparable.weight,
        reason_code: sampleComparable.reason_code,
        amenity_similarity: sampleComparable.amenity_similarity,
        matched_amenities: ["balcony", "security"],
        missing_amenities: [],
      },
    ],
    confidence_factors: sampleValuation.confidence.factors,
    explainability_trace: sampleValuation.explanation_trace.map((item) => ({ ...item })),
    valuation_contract: sampleValuation.valuation_contract ?? {},
    amenity_intelligence: sampleValuation.amenity_intelligence ?? {},
    district_intelligence: {
      active_district: "Central Cairo",
    },
    market_signals: ["Valuation context only"],
    session_state: {},
    evidence: [],
    token_budget: {
      max_context_tokens: 6000,
      estimated_context_tokens: 900,
      truncated: false,
    },
    deterministic_authority: {},
  },
  tool_results: [],
  events: [
    {
      event_id: "event-1",
      stage: "classify_intent",
      event_type: "stage_started",
      message: "Classifying analytical broker intent",
      elapsed_ms: null,
      payload: {},
      created_at: "2026-05-25T00:00:00Z",
    },
  ],
  degraded_mode: false,
  intent_classification: {
    intent: "valuation_explanation",
    confidence: 0.86,
    matched_signals: [],
    fallback: false,
    routing_reason: "Rule-assisted classifier selected the highest-confidence broker intent.",
    has_valuation_request: true,
  },
  reasoning_plan: {
    plan_id: "plan_fixture",
    intent: "valuation_explanation",
    stages: [
      "classify_intent",
      "build_reasoning_plan",
      "execute_tools",
      "assemble_context",
      "generate_narration",
      "validate_grounding",
      "finalize_response",
    ],
    selected_tools: [
      "valuation_analysis",
      "comparable_analysis",
      "explainability",
      "district_intelligence",
      "confidence_analysis",
    ],
    requires_valuation: true,
    evidence_requirements: ["deterministic_authority", "valuation_analysis"],
    narration_mode: "valuation_explainability",
    governance_checks: ["numeric_consistency", "confidence_consistency"],
    degraded_mode_reasons: [],
  },
  narration: {
    provider: "deterministic_formatter",
    model: null,
    used_llm: false,
    latency_ms: 12,
    token_usage: {},
    fallback_reason: null,
  },
  governance: {
    status: "passed",
    checks: [],
    violations: [],
    sanitized: false,
  },
};
