// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFcmPYN7SHdk6OtWmikAMY2ybZNWyyaso',
    appId: '1:11968174472:web:41c15591513721751b023d',
    messagingSenderId: '11968174472',
    projectId: 'valorai-e25b8',
    authDomain: 'valorai-e25b8.firebaseapp.com',
    storageBucket: 'valorai-e25b8.firebasestorage.app',
    measurementId: 'G-XE10J0F6KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Wuif_NGiROdovl-nCzo9sbyet9b21kg',
    appId: '1:11968174472:android:2cc2db96b6d45da81b023d',
    messagingSenderId: '11968174472',
    projectId: 'valorai-e25b8',
    storageBucket: 'valorai-e25b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczg4T9RruqtaWuiEHaHZjvMRLfQxylb0',
    appId: '1:11968174472:ios:ff213221156f15821b023d',
    messagingSenderId: '11968174472',
    projectId: 'valorai-e25b8',
    storageBucket: 'valorai-e25b8.firebasestorage.app',
    iosClientId: '11968174472-tbu6lat4jj66q240sasbnggpvskc40mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterValorai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczg4T9RruqtaWuiEHaHZjvMRLfQxylb0',
    appId: '1:11968174472:ios:ff213221156f15821b023d',
    messagingSenderId: '11968174472',
    projectId: 'valorai-e25b8',
    storageBucket: 'valorai-e25b8.firebasestorage.app',
    iosClientId: '11968174472-tbu6lat4jj66q240sasbnggpvskc40mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterValorai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFcmPYN7SHdk6OtWmikAMY2ybZNWyyaso',
    appId: '1:11968174472:web:94eda1dce555eb071b023d',
    messagingSenderId: '11968174472',
    projectId: 'valorai-e25b8',
    authDomain: 'valorai-e25b8.firebaseapp.com',
    storageBucket: 'valorai-e25b8.firebasestorage.app',
    measurementId: 'G-FBHK0DJLVJ',
  );
}
